### ISSUE TITLE
Alternate interpretation for duplicate choices

### ISSUE THREAD

**Issue by Shroopd** [NebuPookins/JS-Mastermind-Solver#5]
I've been playing a version of Mastermind, where whenever you input a duplicate symbol, instead of only returning the highest success value per color, it returns the success value per slot. The effective result of this is that if it were guess red, red on a solution of red, blue, the alternate game I need to solve returns 1 wrong slot, 1 correct slot while the solver would need a result of only 1 correct slot. The alternate version can be practiced in this \[[discord server's "hacking minigame" channel](https://discord.gg/8JaHgXKx)\], or played as a hacking minigame for that server's game that I ultimately want to beat. I understand if this doesn't fit in the scope of this tool, but adding a toggle for the interpretation of results would be great.

**Comment by NebuPookins** [comment]
Hi @Shroopd ! Thank you for using this program and for your feedback.

Unfortunately, I think what you're describing is a completely different game from Mastermind (even though on the surface they might seem similar). As you mentioned, in Mastermind, it's evaluating the correctness of each peg, whereas in the game you're describing it's evaluating each slot. But there's a more fundamental problem.

In mastermind, each peg actually has 3 possible "correctness levels": 

1. The peg can be the correct color in the correct position.
2. The peg can be the correct color but in the wrong position.
3. The peg can be the incorrect color.

In the game you're describing, it sounds like there's only two possible correctness, because it doesn't make sense to talk about a slot being "in the wrong position".

Because of this difference, I don't think there's much code that can be reused from this solver in the new solver you're looking for. We'd probably have to write a completely new solver from scratch for that.
